FROM johnpapa/angular-cli

# build-time variables
# prod|sandbox its value will be come from outside
ARG env=dev

EXPOSE 4200

RUN apk update && apk add --no-cache make git
# Move our files into directory name "app"

WORKDIR /app
COPY client-ui/package.json /app/
COPY client-ui/package-lock.json  /app/

RUN cd /app && npm install
COPY client-ui/.  /app
# Build with $env variable from outside
RUN cd /app && ng build


CMD ["npm", "start"]


