
version: '3'

services:

  client-ui:
    restart: always
    container_name: client-ui-container
    build:
      context: src
      dockerfile: ./Dockerfile.dev
    image: local/image-client-ui-dev:latest
    command: ["npm", "start"]
    volumes:
      - ./client-ui/src:/app/src
      - ./client-ui/angular.json:/app/angular.json
      - ./client-ui/tsconfig.json:/app/tsconfig.json
      - ./client-ui/tslint.json:/app/tslint.json
    ports:
      - '4200:4200'
